[package]
name = "quickxml_dom"
version = "0.1.0"
authors = ["Alex Shapiro <alexander.max.shapiro@gmail.com>"]

[dev-dependencies]
assert_matches = "1.1"

[dependencies]
lazy_static = "0.2"
quick-xml = "0.9"
regex = "0.2"
